spring:
  datasource:
    url: &dbURL jdbc:mysql://localhost:3306/AngularShop2?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: &dbUser user
    password: &dbPassword 1234
  jpa:
    show_sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  flyway:
    baselineOnMigrate: true
  jackson:
    serialization:
      INDENT_OUTPUT: true