export * from './main/main.component';
export * from './categories/categories.component';
export * from './cart/cart.component';
export * from './checkout/checkout.component';
export * from './contact/contact.component';
export * from './product/product.component';
export * from './register/register.component';
export * from './login/login.component';
export * from './logout/logout.component';
