# Generated by Django 3.0.7 on 2020-06-15 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'Makers',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('tags', models.CharField(max_length=256)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discount', models.IntegerField()),
                ('stock_count', models.IntegerField(db_column='stockCount')),
                ('is_visible', models.BooleanField(db_column='isVisible')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('modifiedDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('maker', models.ForeignKey(db_column='makerId', null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Maker')),
            ],
            options={
                'db_table': 'Products',
                'ordering': ['id'],
            },
        ),
    ]
