# Generated by Django 3.0.7 on 2020-06-19 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_userlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.TextField(max_length=512)),
                ('address2', models.TextField(max_length=512)),
                ('phone', models.TextField(max_length=20)),
                ('to_name', models.TextField(db_column='toName', max_length=256)),
                ('total_price', models.DecimalField(db_column='totalPrice', decimal_places=2, max_digits=15)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='createdDate')),
                ('modified_date', models.DateTimeField(auto_now_add=True, db_column='modifiedDate')),
                ('order_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Payment Accepted'), (2, 'Processing In Progress'), (3, 'On Shipping'), (4, 'Delivered'), (5, 'Delivery Confirmed'), (6, 'Canceled')], db_column='orderStatusId')),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Orders',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=256)),
            ],
            options={
                'db_table': 'OrderStatuses',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('order', models.ForeignKey(db_column='orderId', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.Order')),
                ('product', models.ForeignKey(db_column='productId', on_delete=django.db.models.deletion.CASCADE, related_name='ordered_list', to='shop.Product')),
            ],
            options={
                'db_table': 'OrderItems',
                'ordering': ['id'],
            },
        ),
    ]
